name = "ciapws"
version = "VERSION" 
license = "MIT"
author = "Milan Skocic"
maintainer = "milan.skocic@icloud.com"
copyright = "Copyright 2021-2024, Milan Skocic"
description = "Water properties"
categories  =["Science"]
keywords = ["water", "ciapws", "chemistry"]
homepage = "https://milanskocic.github.io/iapws-docs/index.html"

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = true


[[example]]
name = "example_in_c"
main = "example_in_c.c"

[dependencies]
stdlib = "*"
iapws={git="https://github.com/MilanSkocic/iapws"}
