capi_wp – iapws
capi_wp Subroutine
MIT
16 statements
Source File
public subroutine capi_wp(p, T, prop, res, N, len) bind(C, name="iapws_r797_wp")
C API.
Available properties: * v: specific volume in m3/kg * u: specific internal energy in kJ/kg * s: specific entropy in kJ/kg * h: specific enthalpy in kJ/kg/K * cp: specific isobaric heat capacity in kJ/kg/K * cv: specific isochoric heat capacity in kJ/kg/K * w: speed of sound in m/s
Arguments
Type Intent Optional Attributes Name
real(kind=c_double), intent(in) :: p(N)
Pressure in MPa.
real(kind=c_double), intent(in) :: T(N)
Temperature in K.
type(c_ptr), intent(in), value :: prop
Water property.
real(kind=c_double), intent(out) :: res(N)
Result. Filled with NaNs if gas not found.
integer(kind=c_size_t), intent(in), value :: N
Size of T and p.
integer(kind=c_int), intent(in), value :: len
Size of the prop string.
Calls
Variables
Type Visibility Attributes Name Initial
character(len=1), public, pointer, dimension(:) :: cprop
character(len=len), public :: fprop
integer(kind=int32), public :: i
Call graph
capi_wp calls wp
wp calls find_region, get_r, is1region
find_region calls r4_ps