find_phase – iapws
find_phase Function
MIT
21 statements
Source File
public pure elemental function find_phase(p, T) result(res)
Find the corresponding phase according to p and T. Return the phase as an character: l=LIQUID, v=VAPOR, c=SUPER CRITICAL, s=SATURATION, n=UNKNOWN.
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: p
Pressure in MPa.
real(kind=dp), intent(in) :: T
Temperature in K.
Return Value character(len=1)
Calls
Called by
Call graph
find_phase calls find_region
find_region calls r4_ps
wph calls find_phase
capi_wph calls wph