find_region – iapws
find_region Function
MIT
41 statements
Source File
public pure elemental function find_region(p, T) result(res)
Find the corresponding region according to p and T. Return the number of the region (1 to 5) when found otherwise return -1.
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: p
Pressure in MPa.
real(kind=dp), intent(in) :: T
Temperature in K.
Return Value integer(kind=int32)
Calls
Called by
Call graph
find_region calls r4_ps
find_phase calls find_region
wp calls find_region
wr calls find_region
capi_wp calls wp
capi_wr calls wr
wph calls find_phase
capi_wph calls wph