gases – iapws
gases Function
MIT
31 statements
Source File
public function gases(heavywater) result(list_gases)
Returns the list of available gases.
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: heavywater
Flag if D2O (1) is used or H2O(0).
Return Value type(gas_type), pointer, (:)
Available gases.
Called by
Call graph
capi_gases calls gases
gases2 calls gases
capi_gases2 calls gases2