r1 – iapws
r1 Subroutine
MIT
24 statements
Source File
public pure subroutine r1(p, T, prop, res)
Compute water properties at pressure p in MPa and temperature T in Kelvin. in region 1.
Available properties: * v: specific volume in m3/kg * u: specific internal energy in kJ/kg * s: specific entropy in kJ/kg * h: specific enthalpy in kJ/kg/K * cp: specific isobaric heat capacity in kJ/kg/K * cv: specific isochoric heat capacity in kJ/kg/K * w: speed of sound in m/s
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: p(:)
Pressure in MPa.
real(kind=dp), intent(in) :: T(:)
Pressure in K.
character(len=*), intent(in) :: prop
Property
real(kind=dp), intent(out) :: res(:)
Result
Calls
Call graph
r1 calls r1_cp, r1_cv, r1_h, r1_s, r1_u, r1_v, r1_w