r4_ps – iapws
r4_ps Function
MIT
17 statements
Source File
public pure elemental function r4_ps(Ts) result(value)
Compute the saturation-pressure line. Validity range 273.13 K <= Ts <= 647.096 K.
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: Ts
Saturation temperature in K.
Return Value real(kind=dp)
Saturation Pressure in MPa at temperature Ts. Is nan if Ts is out of range.
Called by
Call graph
find_region calls r4_ps
psat calls r4_ps
capi_psat calls psat
find_phase calls find_region
wp calls find_region
wr calls find_region
capi_wp calls wp
capi_wr calls wr
wph calls find_phase
capi_wph calls wph