wp – iapws
wp Subroutine
MIT
26 statements
Source File
public pure subroutine wp(p, T, prop, res)
Compute water properties at pressure p in MPa and temperature T in Kelvin. The adequate region is selected according to p and T.
Available properties: * v: specific volume in m3/kg * u: specific internal energy in kJ/kg * s: specific entropy in kJ/kg * h: specific enthalpy in kJ/kg/K * cp: specific isobaric heat capacity in kJ/kg/K * cv: specific isochoric heat capacity in kJ/kg/K * w: speed of sound in m/s
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: p(:)
Pressure in MPa.
real(kind=dp), intent(in) :: T(:)
Pressure in K.
character(len=*), intent(in) :: prop
Property
real(kind=dp), intent(out) :: res(:)
Filled with NaN if no adequate region is found.
Calls
Called by
Call graph
wp calls find_region, get_r, is1region
find_region calls r4_ps
capi_wp calls wp