/**
* @file
* @brief Version - autogenerated.
*/

#ifndef iapws_VERSION_H
#define iapws_VERSION_H
#if _MSC_VER
#define ADD_IMPORT __declspec(dllimport)
#else
#define ADD_IMPORT
#endif
ADD_IMPORT extern const char iapws_version_capi_version[ 6];
#endif

