.TH iapws 3 "@DATE@" "@VERSION@" "Library Functions Manual"

.SH NAME
iapws \- library for light and heavy water properties according to IAPWS

.SH LIBRARY
iapws library 
.RI ( libiapws ", " \-liapws )

.SH SYNOPSIS
\"{{{
.IP Fortran 10 
.B use iapws\fP

.IP C 10
.B #include \(dqiapws.h\(dq

.IP Python 10
.B import pyiapws
\"}}}

.SH DESCRIPTION
Numerical implementation for reports:
.RS
.IP \(bu 3
R2-83
.RS
.IP [x] 5
Tc in H2O and D2O
.IP [x] 5
pc in H2O and D2O
.IP [x] 5
rhoc in H2O and D2O
.RE
.IP \(bu 3
G7-04
.RS
.IP [x] 5
kH
.IP [x] 5
kD
.RE
.IP \(bu 3
R7-97
.RS
.IP [x] 5
Region 1
.IP [] 5
Region 2
.IP [] 5
Region 3
.IP [x] 5
Region 4
.IP [] 5
Region 5
.RE
.IP \(bu 3
R11-24:
.RS
.IP [x] 5
Kw
.RE
.RE


.SH NOTES
.PP
dp stands for double precision and it is an alias to real64
from the iso_fortran_env module.

Water phases:
.RS
.TP
l 
liquid
.TP
v 
vapor
.TP
c 
super critical
.TP
s 
saturation
.TP
n 
unknown
.RE

.PP
References
.IP [1] 5 
IAPWS, 
“Release on the Values of Temperature, Pressure and Density of Ordinary and Heavy Water Substances at Their Respective Critical Points.” 
IAPWS, St. Petersburg, Russia, 1992.
.IP [2] 5 W. Wagner and A. Pruss, 
“International Equations for the Saturation Properties of Ordinary Water Substance. Revised According to the International Temperature Scale of 1990. Addendum to J. Phys. Chem. Ref. Data 16, 893 (1987),”,
Journal of Physical and Chemical Reference Data, vol. 22, no. 3, pp. 783–787, May 1993, doi: 10.1063/1.555926.
.IP [3] 5 
A. H. Harvey and E. W. Lemmon, 
“Correlation for the Vapor Pressure of Heavy Water From the Triple Point to the Critical Point,” 
Journal of Physical and Chemical Reference Data, vol. 31, no. 1, pp. 173–181, Mar. 2002, doi: 10.1063/1.1430231.
.IP [4] 5 
W. Wagner and A. Pruß, 
“The IAPWS Formulation 1995 for the Thermodynamic Properties of Ordinary Water Substance for General and Scientific Use,” 
Journal of Physical and Chemical Reference Data, vol. 31, no. 2, pp. 387–535, Jun. 2002, doi: 10.1063/1.1461829.
.IP [5] 5 
R. Fernandez-Prini, J. L. Alvarez, and A. H. Harvey, 
“Henry’s Constants and Vapor–Liquid Distribution Constants for Gaseous Solutes in H2O and D2O at High Temperatures,”
Journal of Physical Chemistry Reference Data, vol. 32, no. 2, pp. 903–916, 2003.
.IP [6] 5 
IAPWS, 
“Guideline on the Henry’s Constant and Vapor-Liquid Distribution Constant for Gases in H2O and D2O at High Temperatures.” 
IAPWS, Kyoto, Japan, 2004.
.IP [7] 5 
A. V. Bandura and S. N. Lvov, 
“The Ionization Constant of Water over Wide Ranges of Temperature and Density,” 
Journal of Physical and Chemical Reference Data, vol. 35, no. 1, pp. 15–30, Mar. 2006, doi: 10.1063/1.1928231.
.IP [8] 5 
IAPWS, 
“Revised Release on the IAPWS Industrial Formulation 1997 for the Thermodynamic Properties of Water and Steam.” 
Lucerne, Switzerland, 2012.
.IP [9] 5 
IAPWS, 
“Revised Release on the IAPWS Formulation 1995 for the Thermodynamic Properties of Ordinary Water Substance for General and Scientific Use.” 
Praque, Czech Republic, 2018.
.IP [10] 5 
IAPWS, 
“Revised Release on the Ionization Constant of H2O.” 
Banff, Canada, 2019.
.IP [11] 5 
H. Arcis et al., 
“Revised Parameters for the IAPWS Formulation for the Ionization Constant of Water Over a Wide Range of Temperatures and Densities, Including Near-Critical Conditions,” 
Journal of Physical and Chemical Reference Data, vol. 53, no. 2, p. 23103, May 2024, doi: 10.1063/5.0198792.
