.TH iapws_version 3 "07 août 2026" "0.7.1" "Library Functions Manual"

.SH NAME
\"{{{
version \- get the library version
\"}}}

.SH LIBRARY
\"{{{
Codata library 
.RI ( libiapws ", " \-liapws )
\"}}}

.SH SYNOPSIS
\"{{{ 
.IP Fortran 10
.BI "function version()result(" fptr ")"
.RS
.IP "" 3
.BI "character(len=:), pointer :: " fptr 
.RE

.IP C 10
.B char* iapws_version()

.IP Python 10
.BI str: pyiapws.__version__
\"}}}

.SH DESCRIPTION
\"{{{
Get the library version.
\"}}}

.SH RETURN VALUE
\"{{{
.IP pointer 10 
Pointer to the version string.
\"}}}

.SH EXAMPLE
\"{{{
.PP
Fortran:
.nf
.ft CR
    use iapws
    print *, "version = ", version()
.ft R
.fi

.PP
C:
.nf
.ft CR
    include <stdio.h>
    include "iapws.h"
    printf("version = %s\\n", iapws_version());
.ft R
.fi

.PP
Python:
.nf
.ft CR
    import pyiapws
    print(f"version = {pyiapws.__version__}")
.ft R
.fi
\"}}}

.SH SEE ALSO
.BR iapws (3)
.BR iapws_cli (1)
.BR iapws_kh (3)
.BR ciaaw (3),
.BR codata (3),
