module iapws__version_capi
!! Version C API - autogenerated.
use iso_c_binding
implicit none
private

character(kind=c_char), protected, public, bind(C) :: iapws_version_capi_version( 6) = &
["0", ".", "2", ".", "2", c_null_char]

end module iapws__version_capi
